package GUI.Admin;

import GUI.Admin.Document.*;
import GUI.Admin.User.*;
import GUI.BackgroundPanel;
import GUI.Login.Login;
import Database_connection.DatabaseManager;
import main_class.Admin;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.*;

/**
 * @author Quach Quang
 */
public class MainViewAdmin extends javax.swing.JFrame {

  String idAdmin;

  /**
   * Creates new form MainViewAdmin
   */
  public MainViewAdmin(String idAdmin) {
    this.idAdmin = idAdmin;
    initComponents();
    setSize(1050, 550);
    setLocationRelativeTo(null);
    backgroundPanel.setBackground(Color.WHITE);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents(){

    backgroundPanel = new BackgroundPanel("/image/backgroundAdmin.png");

    titleAdminLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    adminTextArea = new javax.swing.JTextArea();
    findDocumentButton = new javax.swing.JButton();
    borrowDocumentButton = new javax.swing.JButton();
    returnDocumentButton = new javax.swing.JButton();
    backButton = new javax.swing.JButton();
    addUserButton = new javax.swing.JButton();
    addAdminButton = new javax.swing.JButton();
    addDocumentButton = new javax.swing.JButton();
    deleteUserButton = new javax.swing.JButton();
    deleteAdminButton = new javax.swing.JButton();
    deleteDocumentButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    titleAdminLabel.setFont(new java.awt.Font("Sitka Banner", 3, 24)); // NOI18N
    titleAdminLabel.setForeground(new java.awt.Color(13, 112, 106));
    titleAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleAdminLabel.setText("ADMINISTRATOR TASKS");

    adminTextArea.setEditable(false);
    adminTextArea.setColumns(20);
    adminTextArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
    adminTextArea.setRows(1);
    adminTextArea.setTabSize(6);
    adminTextArea.addAncestorListener(new javax.swing.event.AncestorListener() {
      public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
        adminTextAreaAncestorAdded(evt);
      }
      public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
      }
      public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
      }
    });
    jScrollPane1.setViewportView(adminTextArea);

    findDocumentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    findDocumentButton.setText("Search Document");
    findDocumentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        findDocumentButtonActionPerformed(evt);
      }
    });

    borrowDocumentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    borrowDocumentButton.setText("Borrow Document");
    borrowDocumentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        borrowDocumentButtonActionPerformed(evt);
      }
    });

    returnDocumentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    returnDocumentButton.setText("Return Document");
    returnDocumentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        returnDocumentButtonActionPerformed(evt);
      }
    });

    backButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    backButton.setText("Sign Out");
    backButton.setBackground(Color.cyan);
    backButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backButtonActionPerformed(evt);
      }
    });

    addUserButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    addUserButton.setText("Add User");
    addUserButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addUserButtonActionPerformed(evt);
      }
    });

    addAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    addAdminButton.setText("Add Admin");
    addAdminButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addAdminButtonActionPerformed(evt);
      }
    });

    addDocumentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    addDocumentButton.setText("Add Document");
    addDocumentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addDocumentButtonActionPerformed(evt);
      }
    });

    deleteUserButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    deleteUserButton.setText("Delete User");
    deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteUserButtonActionPerformed(evt);
      }
    });

    deleteAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    deleteAdminButton.setText("Delete Admin");
    deleteAdminButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteAdminButtonActionPerformed(evt);
      }
    });

    deleteDocumentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    deleteDocumentButton.setText("Delete Document");
    deleteDocumentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteDocumentButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
    backgroundPanel.setLayout(backgroundPanelLayout);
    backgroundPanelLayout.setHorizontalGroup(
        backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleAdminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(findDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(borrowDocumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(returnDocumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addDocumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteDocumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(deleteUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))))
    );
    backgroundPanelLayout.setVerticalGroup(
        backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleAdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrowDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(returnDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDocumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deleteDocumentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>

  private void addDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new AddDocumentAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa s�� hiện tại nếu cần
  }

  private void addAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new AddAdminAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa s�� hiện tại nếu cần
  }

  private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new AddUserAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa s�� hiện tại nếu cần
  }

  private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new Login().setVisible(true);
    this.dispose();
  }

  private void returnDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new UpdateReturnedDocumentAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa s�� hiện tại nếu cần
  }

  private void borrowDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new UpdateBorrowedDocumentAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa sổ hiện tại nếu cần
  }

  private void findDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new FindDocumentAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa sổ hiện tại nếu cần
  }

  private void adminTextAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {
    // Khởi tạo đối tượng DatabaseManager
    DatabaseManager dbManager = new DatabaseManager();

    // Tìm thông tin người dùng dựa trên idUser
    Admin admin = dbManager.findAdmin(idAdmin);

    // Kiểm tra nếu tìm thấy người dùng
    if (admin != null) {
      // Hiển thị thông tin người dùng lên userTextArea
      StringBuilder adminInfo = new StringBuilder();
      adminInfo.append("Admin ID: ").append(admin.getId()).append("\n\n")
          .append("Name: ").append(admin.getName()).append("\n\n")
          .append("Position: ").append(admin.getPosition()).append("\n\n")
          .append("|-------------------------------------------------------");
      adminTextArea.setText(adminInfo.toString());
    } else {
      adminTextArea.setText("Không tìm thấy thông tin người dùng!");
    }
  }

  private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new DeleteUserAdmin(idAdmin).setVisible(true);
    this.dispose(); // Đóng cửa sổ hiện tại nếu cần
  }

  private void deleteAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new DeleteAdminAdmin(idAdmin).setVisible(true);
    this.dispose();
  }

  private void deleteDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
    new DeleteDocumentAdmin(idAdmin).setVisible(true);
    this.dispose();
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainViewAdmin.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainViewAdmin.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainViewAdmin.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainViewAdmin.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainViewAdmin("22022132").setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JButton addAdminButton;
  private javax.swing.JButton addDocumentButton;
  private javax.swing.JButton addUserButton;
  private javax.swing.JTextArea adminTextArea;
  private javax.swing.JButton backButton;
  private javax.swing.JPanel backgroundPanel;
  private javax.swing.JButton borrowDocumentButton;
  private javax.swing.JButton deleteAdminButton;
  private javax.swing.JButton deleteDocumentButton;
  private javax.swing.JButton deleteUserButton;
  private javax.swing.JButton findDocumentButton;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JButton returnDocumentButton;
  private javax.swing.JLabel titleAdminLabel;
  // End of variables declaration
}

